import db from './src/db.ts';

const questions = [
  { tema: 'TEMA 17 - PRESUPUESTO DEL ESTADO', pregunta: '¿Qué son los Presupuestos Generales del Estado?', opcion_a: 'Un plan de gobierno', opcion_b: 'Una ley ordinaria', opcion_c: 'Un reglamento', opcion_d: 'Expresión cifrada de derechos y obligaciones del sector público estatal', correcta: 'd' },
  { tema: 'TEMA 17 - PRESUPUESTO DEL ESTADO', pregunta: '¿Quién elabora los PGE?', opcion_a: 'Las Cortes Generales', opcion_b: 'El Tribunal de Cuentas', opcion_c: 'El Banco de España', opcion_d: 'El Gobierno', correcta: 'd' },
  { tema: 'TEMA 17 - PRESUPUESTO DEL ESTADO', pregunta: '¿Quién aprueba los PGE?', opcion_a: 'El Gobierno', opcion_b: 'El Rey', opcion_c: 'El Tribunal Constitucional', opcion_d: 'Las Cortes Generales', correcta: 'd' },
  { tema: 'TEMA 17 - PRESUPUESTO DEL ESTADO', pregunta: '¿Qué carácter tienen los PGE?', opcion_a: 'Plurianual', opcion_b: 'Semestral', opcion_c: 'Trimestral', opcion_d: 'Anual', correcta: 'd' },
  { tema: 'TEMA 17 - PRESUPUESTO DEL ESTADO', pregunta: '¿Cuándo debe presentar el Gobierno los PGE al Congreso?', opcion_a: '1 mes antes', opcion_b: '6 meses antes', opcion_c: 'Al inicio del ejercicio', opcion_d: 'Al menos 3 meses antes de expiración de los anteriores', correcta: 'd' },
  { tema: 'TEMA 17 - PRESUPUESTO DEL ESTADO', pregunta: '¿Qué fecha límite hay para presentar PGE?', opcion_a: 'Antes del 1 de noviembre', opcion_b: 'Antes del 1 de diciembre', opcion_c: 'Antes del 31 de diciembre', opcion_d: 'Antes del 1 de octubre', correcta: 'd' },
  { tema: 'TEMA 17 - PRESUPUESTO DEL ESTADO', pregunta: '¿Qué ocurre si no se aprueban los PGE antes del 1 de enero?', opcion_a: 'Se paraliza la Administración', opcion_b: 'Se convocan elecciones', opcion_c: 'Se elaboran nuevos inmediatamente', opcion_d: 'Se prorrogan automáticamente los del ejercicio anterior', correcta: 'd' },
  { tema: 'TEMA 17 - PRESUPUESTO DEL ESTADO', pregunta: '¿Pueden los PGE crear tributos?', opcion_a: 'Sí, siempre', opcion_b: 'Solo impuestos indirectos', opcion_c: 'Solo tasas', opcion_d: 'No, no pueden crear tributos', correcta: 'd' },
  { tema: 'TEMA 17 - PRESUPUESTO DEL ESTADO', pregunta: '¿Qué artículo de la CE regula los PGE?', opcion_a: 'Artículo 135', opcion_b: 'Artículo 136', opcion_c: 'Artículo 137', opcion_d: 'Artículo 134', correcta: 'd' },
  { tema: 'TEMA 17 - PRESUPUESTO DEL ESTADO', pregunta: '¿Qué principio consagra el artículo 135 CE?', opcion_a: 'Legalidad', opcion_b: 'Anualidad', opcion_c: 'Universalidad', opcion_d: 'Estabilidad presupuestaria', correcta: 'd' },
  { tema: 'TEMA 17 - PRESUPUESTO DEL ESTADO', pregunta: '¿Qué Ley regula los PGE?', opcion_a: 'Ley 39/2015', opcion_b: 'Ley 40/2015', opcion_c: 'Ley 30/1992', opcion_d: 'Ley 47/2003 General Presupuestaria', correcta: 'd' },
  { tema: 'TEMA 17 - PRESUPUESTO DEL ESTADO', pregunta: '¿Qué principio significa que todos los ingresos financian todos los gastos?', opcion_a: 'Principio de universalidad', opcion_b: 'Principio de anualidad', opcion_c: 'Principio de especialidad', opcion_d: 'Principio de no afectación', correcta: 'd' },
  { tema: 'TEMA 17 - PRESUPUESTO DEL ESTADO', pregunta: '¿Qué principio significa que los créditos son para gastos concretos?', opcion_a: 'Principio de no afectación', opcion_b: 'Principio de anualidad', opcion_c: 'Principio de universalidad', opcion_d: 'Principio de especialidad', correcta: 'd' },
  { tema: 'TEMA 17 - PRESUPUESTO DEL ESTADO', pregunta: '¿Qué clasificación de gastos responde a "¿quién gasta"?', opcion_a: 'Clasificación económica', opcion_b: 'Clasificación por programas', opcion_c: 'Clasificación funcional', opcion_d: 'Clasificación orgánica', correcta: 'd' },
  { tema: 'TEMA 17 - PRESUPUESTO DEL ESTADO', pregunta: '¿Qué clasificación de gastos responde a "en qué se gasta"?', opcion_a: 'Clasificación orgánica', opcion_b: 'Clasificación económica', opcion_c: 'Clasificación territorial', opcion_d: 'Clasificación por programas', correcta: 'd' },
  { tema: 'TEMA 17 - PRESUPUESTO DEL ESTADO', pregunta: '¿Qué clasificación de gastos responde a "cómo gasta"?', opcion_a: 'Clasificación orgánica', opcion_b: 'Clasificación por programas', opcion_c: 'Clasificación funcional', opcion_d: 'Clasificación económica', correcta: 'd' },
  { tema: 'TEMA 17 - PRESUPUESTO DEL ESTADO', pregunta: '¿En cuántas clasificaciones se presentan los gastos?', opcion_a: 'Dos', opcion_b: 'Cuatro', opcion_c: 'Una', opcion_d: 'Tres: orgánica, por programas y económica', correcta: 'd' },
  { tema: 'TEMA 17 - PRESUPUESTO DEL ESTADO', pregunta: '¿En cuántas clasificaciones se presentan los ingresos?', opcion_a: 'Tres', opcion_b: 'Cuatro', opcion_c: 'Una', opcion_d: 'Dos: orgánica y económica', correcta: 'd' },
  { tema: 'TEMA 17 - PRESUPUESTO DEL ESTADO', pregunta: '¿Qué capítulo de gastos es "Gastos de personal"?', opcion_a: 'Capítulo 2', opcion_b: 'Capítulo 3', opcion_c: 'Capítulo 4', opcion_d: 'Capítulo 1', correcta: 'd' },
  { tema: 'TEMA 17 - PRESUPUESTO DEL ESTADO', pregunta: '¿Qué capítulo es "Gastos corrientes en bienes y servicios"?', opcion_a: 'Capítulo 1', opcion_b: 'Capítulo 3', opcion_c: 'Capítulo 4', opcion_d: 'Capítulo 2', correcta: 'd' },
  { tema: 'TEMA 17 - PRESUPUESTO DEL ESTADO', pregunta: '¿Qué capítulo es "Gastos financieros"?', opcion_a: 'Capítulo 1', opcion_b: 'Capítulo 2', opcion_c: 'Capítulo 4', opcion_d: 'Capítulo 3', correcta: 'd' },
  { tema: 'TEMA 17 - PRESUPUESTO DEL ESTADO', pregunta: '¿Qué capítulo es "Transferencias corrientes"?', opcion_a: 'Capítulo 1', opcion_b: 'Capítulo 2', opcion_c: 'Capítulo 3', opcion_d: 'Capítulo 4', correcta: 'd' },
  { tema: 'TEMA 17 - PRESUPUESTO DEL ESTADO', pregunta: '¿Qué capítulo es "Inversiones reales"?', opcion_a: 'Capítulo 1', opcion_b: 'Capítulo 2', opcion_c: 'Capítulo 3', opcion_d: 'Capítulo 6', correcta: 'd' },
  { tema: 'TEMA 17 - PRESUPUESTO DEL ESTADO', pregunta: '¿Qué capítulo es "Transferencias de capital"?', opcion_a: 'Capítulo 1', opcion_b: 'Capítulo 6', opcion_c: 'Capítulo 8', opcion_d: 'Capítulo 7', correcta: 'd' },
  { tema: 'TEMA 17 - PRESUPUESTO DEL ESTADO', pregunta: '¿Qué capítulo es "Activos financieros"?', opcion_a: 'Capítulo 1', opcion_b: 'Capítulo 6', opcion_c: 'Capítulo 7', opcion_d: 'Capítulo 8', correcta: 'd' },
  { tema: 'TEMA 17 - PRESUPUESTO DEL ESTADO', pregunta: '¿Qué capítulo es "Pasivos financieros"?', opcion_a: 'Capítulo 1', opcion_b: 'Capítulo 8', opcion_c: 'Capítulo 7', opcion_d: 'Capítulo 9', correcta: 'd' },
  { tema: 'TEMA 17 - PRESUPUESTO DEL ESTADO', pregunta: '¿Qué capítulo de ingresos es "Impuestos directos"?', opcion_a: 'Capítulo 2', opcion_b: 'Capítulo 3', opcion_c: 'Capítulo 4', opcion_d: 'Capítulo 1', correcta: 'd' },
  { tema: 'TEMA 17 - PRESUPUESTO DEL ESTADO', pregunta: '¿Qué capítulo de ingresos es "Impuestos indirectos"?', opcion_a: 'Capítulo 1', opcion_b: 'Capítulo 3', opcion_c: 'Capítulo 4', opcion_d: 'Capítulo 2', correcta: 'd' },
  { tema: 'TEMA 17 - PRESUPUESTO DEL ESTADO', pregunta: '¿Qué capítulo de ingresos es "Tasas y precios públicos"?', opcion_a: 'Capítulo 1', opcion_b: 'Capítulo 2', opcion_c: 'Capítulo 4', opcion_d: 'Capítulo 3', correcta: 'd' },
  { tema: 'TEMA 17 - PRESUPUESTO DEL ESTADO', pregunta: '¿Qué capítulo de ingresos es "Ingresos patrimoniales"?', opcion_a: 'Capítulo 1', opcion_b: 'Capítulo 3', opcion_c: 'Capítulo 4', opcion_d: 'Capítulo 5', correcta: 'd' },
  { tema: 'TEMA 17 - PRESUPUESTO DEL ESTADO', pregunta: '¿Qué ciclo tiene el presupuesto?', opcion_a: 'Solo elaboración y aprobación', opcion_b: 'Solo ejecución', opcion_c: 'Solo control', opcion_d: 'Elaboración, aprobación, ejecución y control', correcta: 'd' },
  { tema: 'TEMA 17 - PRESUPUESTO DEL ESTADO', pregunta: '¿Qué fase corresponde al Gobierno?', opcion_a: 'Aprobación y control', opcion_b: 'Solo aprobación', opcion_c: 'Solo control', opcion_d: 'Elaboración y ejecución', correcta: 'd' },
  { tema: 'TEMA 17 - PRESUPUESTO DEL ESTADO', pregunta: '¿Qué fase corresponde a las Cortes?', opcion_a: 'Elaboración y ejecución', opcion_b: 'Solo elaboración', opcion_c: 'Solo ejecución', opcion_d: 'Aprobación y control', correcta: 'd' },
  { tema: 'TEMA 17 - PRESUPUESTO DEL ESTADO', pregunta: '¿Quién ejerce el control externo?', opcion_a: 'Intervención General', opcion_b: 'Las Cortes', opcion_c: 'El Gobierno', opcion_d: 'Tribunal de Cuentas', correcta: 'd' },
  { tema: 'TEMA 17 - PRESUPUESTO DEL ESTADO', pregunta: '¿Quién ejerce el control interno?', opcion_a: 'Tribunal de Cuentas', opcion_b: 'Las Cortes', opcion_c: 'El Gobierno', opcion_d: 'Intervención General de la Administración del Estado', correcta: 'd' },
  { tema: 'TEMA 17 - PRESUPUESTO DEL ESTADO', pregunta: '¿Cuáles son las fases de ejecución del gasto?', opcion_a: 'Solo aprobación y pago', opcion_b: 'Solo compromiso', opcion_c: 'Solo reconocimiento', opcion_d: 'Aprobación, compromiso, reconocimiento y pago', correcta: 'd' },
  { tema: 'TEMA 17 - PRESUPUESTO DEL ESTADO', pregunta: '¿Qué fase corresponde al Gobierno?', opcion_a: 'Solo aprobación', opcion_b: 'Solo control', opcion_c: 'Solo elaboración', opcion_d: 'Elaboración y ejecución', correcta: 'd' },
  { tema: 'TEMA 17 - PRESUPUESTO DEL ESTADO', pregunta: '¿Qué documento se expide en aprobación?', opcion_a: 'Documento D', opcion_b: 'Documento O', opcion_c: 'Documento K', opcion_d: 'Documento A', correcta: 'd' },
  { tema: 'TEMA 17 - PRESUPUESTO DEL ESTADO', pregunta: '¿Qué documento se expide en compromiso?', opcion_a: 'Documento A', opcion_b: 'Documento O', opcion_c: 'Documento K', opcion_d: 'Documento D', correcta: 'd' },
  { tema: 'TEMA 17 - PRESUPUESTO DEL ESTADO', pregunta: '¿Qué documento se expide en reconocimiento?', opcion_a: 'Documento A', opcion_b: 'Documento D', opcion_c: 'Documento K', opcion_d: 'Documento O o OK', correcta: 'd' },
  { tema: 'TEMA 17 - PRESUPUESTO DEL ESTADO', pregunta: '¿Quién ordena los pagos del Estado?', opcion_a: 'El Ministro de Hacienda', opcion_b: 'El Interventor General', opcion_c: 'El Presidente del Gobierno', opcion_d: 'Director General del Tesoro y Política Financiera', correcta: 'd' },
  { tema: 'TEMA 17 - PRESUPUESTO DEL ESTADO', pregunta: '¿Qué es el Fondo de Contingencia?', opcion_a: 'Un fondo de pensiones', opcion_b: 'Un fondo de inversión', opcion_c: 'Un fondo de reserva', opcion_d: 'Crédito para necesidades imprevistas (2% del gasto no financiero)', correcta: 'd' },
  { tema: 'TEMA 17 - PRESUPUESTO DEL ESTADO', pregunta: '¿Qué programas son finalistas?', opcion_a: 'Los de apoyo', opcion_b: 'Los de gestión', opcion_c: 'Los instrumentales', opcion_d: 'Los destinados directamente a producción de bienes o servicios', correcta: 'd' },
  { tema: 'TEMA 17 - PRESUPUESTO DEL ESTADO', pregunta: '¿Qué programas son instrumentales?', opcion_a: 'Los finalistas', opcion_b: 'Los de sanidad', opcion_c: 'Los de educación', opcion_d: 'Los de apoyo, gestión e infraestructura', correcta: 'd' },
  { tema: 'TEMA 17 - PRESUPUESTO DEL ESTADO', pregunta: '¿A qué nivel se especifican créditos para personal?', opcion_a: 'A nivel de concepto', opcion_b: 'A nivel de capítulo', opcion_c: 'A nivel de subconcepto', opcion_d: 'A nivel de artículo', correcta: 'd' },
  { tema: 'TEMA 17 - PRESUPUESTO DEL ESTADO', pregunta: '¿A qué nivel se especifican inversiones reales en AGE?', opcion_a: 'A nivel de artículo', opcion_b: 'A nivel de concepto', opcion_c: 'A nivel de subconcepto', opcion_d: 'A nivel de capítulo', correcta: 'd' },
  { tema: 'TEMA 17 - PRESUPUESTO DEL ESTADO', pregunta: '¿Qué es la contabilidad presupuestaria?', opcion_a: 'Contabilidad de empresas', opcion_b: 'Contabilidad financiera', opcion_c: 'Auditoría', opcion_d: 'Registro y control de ejecución de ingresos y gastos', correcta: 'd' },
  { tema: 'TEMA 17 - PRESUPUESTO DEL ESTADO', pregunta: '¿Qué Ley regula la estabilidad presupuestaria?', opcion_a: 'Ley 47/2003', opcion_b: 'Ley 39/2015', opcion_c: 'Ley 40/2015', opcion_d: 'Ley Orgánica 2/2012', correcta: 'd' },
  { tema: 'TEMA 17 - PRESUPUESTO DEL ESTADO', pregunta: '¿Qué principio significa que el presupuesto tiene horizonte anual?', opcion_a: 'Principio de plurianualidad', opcion_b: 'Principio de transparencia', opcion_c: 'Principio de eficiencia', opcion_d: 'Principio de anualidad', correcta: 'd' },
  { tema: 'TEMA 17 - PRESUPUESTO DEL ESTADO', pregunta: '¿Qué fase del ciclo presupuestario es la última?', opcion_a: 'La elaboración', opcion_b: 'La aprobación', opcion_c: 'La ejecución', opcion_d: 'El control', correcta: 'd' }
];

const stmt = db.prepare("INSERT INTO preguntas (tema, pregunta, opcion_a, opcion_b, opcion_c, opcion_d, correcta) VALUES (?, ?, ?, ?, ?, ?, ?)");
const insertMany = db.transaction((qs) => {
  for (const q of qs) {
    stmt.run(q.tema, q.pregunta, q.opcion_a, q.opcion_b, q.opcion_c, q.opcion_d, q.correcta);
  }
});
insertMany(questions);
console.log('Seeded TEMA 17 questions');
