import db from './src/db.ts';

const questions = [
  { tema: 'TEMA 20 - PROTECCIÓN DE DATOS', pregunta: '¿Qué ley regula protección de datos en España?', opcion_a: 'Ley 39/2015', opcion_b: 'Ley 40/2015', opcion_c: 'Ley 47/2003', opcion_d: 'Ley Orgánica 3/2018 (LOPDGDD)', correcta: 'd' },
  { tema: 'TEMA 20 - PROTECCIÓN DE DATOS', pregunta: '¿Qué Reglamento europeo complementa la LOPDGDD?', opcion_a: 'Directiva 95/46/CE', opcion_b: 'Reglamento 2018/1725', opcion_c: 'Directiva 2002/58/CE', opcion_d: 'RGPD (UE) 2016/679', correcta: 'd' },
  { tema: 'TEMA 20 - PROTECCIÓN DE DATOS', pregunta: '¿Cuándo entró en vigor la LOPDGDD?', opcion_a: '1 de enero de 2019', opcion_b: '25 de mayo de 2018', opcion_c: '6 de diciembre de 2018', opcion_d: '7 de diciembre de 2018', correcta: 'd' },
  { tema: 'TEMA 20 - PROTECCIÓN DE DATOS', pregunta: '¿Qué artículo de la CE ampara protección de datos?', opcion_a: 'Artículo 14', opcion_b: 'Artículo 20', opcion_c: 'Artículo 24', opcion_d: 'Artículo 18.4', correcta: 'd' },
  { tema: 'TEMA 20 - PROTECCIÓN DE DATOS', pregunta: '¿A qué tratamientos se aplica la LOPDGDD?', opcion_a: 'Solo automatizados', opcion_b: 'Solo no automatizados', opcion_c: 'Solo en papel', opcion_d: 'Tratamientos automatizados y no automatizados en ficheros', correcta: 'd' },
  { tema: 'TEMA 20 - PROTECCIÓN DE DATOS', pregunta: '¿Se aplica a datos de personas fallecidas?', opcion_a: 'Sí, siempre', opcion_b: 'No, nunca', opcion_c: 'Solo si lo piden herederos', opcion_d: 'No, salvo excepciones del artículo 3', correcta: 'd' },
  { tema: 'TEMA 20 - PROTECCIÓN DE DATOS', pregunta: '¿Quién puede acceder a datos de fallecido?', opcion_a: 'Cualquier persona', opcion_b: 'Solo el Ministerio Fiscal', opcion_c: 'Nadie', opcion_d: 'Familiares, herederos o personas designadas', correcta: 'd' },
  { tema: 'TEMA 20 - PROTECCIÓN DE DATOS', pregunta: '¿Puede el fallecido prohibir acceso a sus datos?', opcion_a: 'No, nunca', opcion_b: 'Solo si es menor', opcion_c: 'Solo si hay testamento', opcion_d: 'Sí, mediante prohibición expresa', correcta: 'd' },
  { tema: 'TEMA 20 - PROTECCIÓN DE DATOS', pregunta: '¿Qué principio exige datos exactos y actualizados?', opcion_a: 'Principio de licitud', opcion_b: 'Principio de transparencia', opcion_c: 'Principio de minimización', opcion_d: 'Principio de exactitud', correcta: 'd' },
  { tema: 'TEMA 20 - PROTECCIÓN DE DATOS', pregunta: '¿Quién tiene deber de confidencialidad?', opcion_a: 'Solo el responsable', opcion_b: 'Solo el encargado', opcion_c: 'Solo los funcionarios', opcion_d: 'Responsables, encargados y todas las personas que intervengan', correcta: 'd' },
  { tema: 'TEMA 20 - PROTECCIÓN DE DATOS', pregunta: '¿Cuánto dura el deber de confidencialidad?', opcion_a: 'Solo durante la relación', opcion_b: '1 año tras finalizar', opcion_c: '5 años', opcion_d: 'Indefinidamente, incluso tras finalizar relación', correcta: 'd' },
  { tema: 'TEMA 20 - PROTECCIÓN DE DATOS', pregunta: '¿Qué es el consentimiento?', opcion_a: 'Una autorización tácita', opcion_b: 'Una presunción', opcion_c: 'Una obligación', opcion_d: 'Manifestación libre, específica, informada e inequívoca', correcta: 'd' },
  { tema: 'TEMA 20 - PROTECCIÓN DE DATOS', pregunta: '¿Desde qué edad pueden consentir menores?', opcion_a: '16 años', opcion_b: '18 años', opcion_c: '12 años', opcion_d: '14 años', correcta: 'd' },
  { tema: 'TEMA 20 - PROTECCIÓN DE DATOS', pregunta: '¿Quién consiente para menores de 14 años?', opcion_a: 'El menor', opcion_b: 'El Ministerio Fiscal', opcion_c: 'El centro educativo', opcion_d: 'Titulares de patria potestad o tutela', correcta: 'd' },
  { tema: 'TEMA 20 - PROTECCIÓN DE DATOS', pregunta: '¿Qué base legitima tratamiento por obligación legal?', opcion_a: 'Cualquier norma', opcion_b: 'Solo reglamento', opcion_c: 'Solo orden ministerial', opcion_d: 'Norma con rango de ley', correcta: 'd' },
  { tema: 'TEMA 20 - PROTECCIÓN DE DATOS', pregunta: '¿Qué datos son categorías especiales?', opcion_a: 'Nombre y apellidos', opcion_b: 'DNI y dirección', opcion_c: 'Teléfono y email', opcion_d: 'Ideología, afiliación sindical, religión, orientación sexual, salud', correcta: 'd' },
  { tema: 'TEMA 20 - PROTECCIÓN DE DATOS', pregunta: '¿Basta consentimiento para datos de ideología?', opcion_a: 'Sí, siempre', opcion_b: 'Solo si es mayor de edad', opcion_c: 'Solo si es por escrito', opcion_d: 'No, se necesita norma con rango de ley', correcta: 'd' },
  { tema: 'TEMA 20 - PROTECCIÓN DE DATOS', pregunta: '¿Qué datos son de naturaleza penal?', opcion_a: 'Datos de salud', opcion_b: 'Datos económicos', opcion_c: 'Datos laborales', opcion_d: 'Condenas e infracciones penales', correcta: 'd' },
  { tema: 'TEMA 20 - PROTECCIÓN DE DATOS', pregunta: '¿Quién puede tratar datos penales?', opcion_a: 'Cualquier empresa', opcion_b: 'Solo la Policía', opcion_c: 'Solo los Jueces', opcion_d: 'Solo con norma legal o para ejercicio de funciones jurídicas', correcta: 'd' },
  { tema: 'TEMA 20 - PROTECCIÓN DE DATOS', pregunta: '¿Qué derecho permite saber qué datos tienen?', opcion_a: 'Derecho de rectificación', opcion_b: 'Derecho de supresión', opcion_c: 'Derecho de oposición', opcion_d: 'Derecho de acceso', correcta: 'd' },
  { tema: 'TEMA 20 - PROTECCIÓN DE DATOS', pregunta: '¿Qué derecho permite corregir datos inexactos?', opcion_a: 'Derecho de acceso', opcion_b: 'Derecho de supresión', opcion_c: 'Derecho de portabilidad', opcion_d: 'Derecho de rectificación', correcta: 'd' },
  { tema: 'TEMA 20 - PROTECCIÓN DE DATOS', pregunta: '¿Qué derecho es el "derecho al olvido"?', opcion_a: 'Derecho de acceso', opcion_b: 'Derecho de rectificación', opcion_c: 'Derecho de limitación', opcion_d: 'Derecho de supresión', correcta: 'd' },
  { tema: 'TEMA 20 - PROTECCIÓN DE DATOS', pregunta: '¿Qué derecho permite pausar tratamiento?', opcion_a: 'Derecho de acceso', opcion_b: 'Derecho de supresión', opcion_c: 'Derecho de portabilidad', opcion_d: 'Derecho a la limitación del tratamiento', correcta: 'd' },
  { tema: 'TEMA 20 - PROTECCIÓN DE DATOS', pregunta: '¿Qué derecho permite llevarse los datos?', opcion_a: 'Derecho de acceso', opcion_b: 'Derecho de supresión', opcion_c: 'Derecho de oposición', opcion_d: 'Derecho a la portabilidad', correcta: 'd' },
  { tema: 'TEMA 20 - PROTECCIÓN DE DATOS', pregunta: '¿Qué derecho permite decir "no" al marketing?', opcion_a: 'Derecho de acceso', opcion_b: 'Derecho de rectificación', opcion_c: 'Derecho de portabilidad', opcion_d: 'Derecho de oposición', correcta: 'd' },
  { tema: 'TEMA 20 - PROTECCIÓN DE DATOS', pregunta: '¿Son gratuitos los derechos ARCO?', opcion_a: 'No, siempre se paga', opcion_b: 'Solo el acceso', opcion_c: 'Solo la rectificación', opcion_d: 'Sí, las actuaciones son gratuitas', correcta: 'd' },
  { tema: 'TEMA 20 - PROTECCIÓN DE DATOS', pregunta: '¿Cuándo se puede cobrar por ejercicio de derechos?', opcion_a: 'Nunca', opcion_b: 'Siempre', opcion_c: 'Solo para empresas', opcion_d: 'Cuando solicitudes sean repetitivas o excesivas', correcta: 'd' },
  { tema: 'TEMA 20 - PROTECCIÓN DE DATOS', pregunta: '¿Qué es la AEPD?', opcion_a: 'Agencia Estatal de Publicidad', opcion_b: 'Asociación de Empresas de Protección', opcion_c: 'Administración de Empleo Público', opcion_d: 'Agencia Española de Protección de Datos', correcta: 'd' },
  { tema: 'TEMA 20 - PROTECCIÓN DE DATOS', pregunta: '¿Qué naturaleza tiene la AEPD?', opcion_a: 'Organismo autónomo', opcion_b: 'Ministerio', opcion_c: 'Tribunal', opcion_d: 'Autoridad administrativa independiente', correcta: 'd' },
  { tema: 'TEMA 20 - PROTECCIÓN DE DATOS', pregunta: '¿Con qué Ministerio se relaciona la AEPD?', opcion_a: 'Ministerio del Interior', opcion_b: 'Ministerio de Hacienda', opcion_c: 'Ministerio de Economía', opcion_d: 'Ministerio de Justicia', correcta: 'd' },
  { tema: 'TEMA 20 - PROTECCIÓN DE DATOS', pregunta: '¿Quién nombra al Presidente de la AEPD?', opcion_a: 'El Congreso', opcion_b: 'El Senado', opcion_c: 'El Rey', opcion_d: 'Gobierno, a propuesta de Ministerio de Justicia', correcta: 'd' },
  { tema: 'TEMA 20 - PROTECCIÓN DE DATOS', pregunta: '¿Cuánto dura el mandato del Presidente de AEPD?', opcion_a: '3 años', opcion_b: '4 años', opcion_c: '6 años', opcion_d: '5 años, renovable', correcta: 'd' },
  { tema: 'TEMA 20 - PROTECCIÓN DE DATOS', pregunta: '¿Qué mayoría necesita ratificación del Presidente?', opcion_a: 'Mayoría simple', opcion_b: 'Mayoría absoluta', opcion_c: 'Unanimidad', opcion_d: 'Tres quintos en primera votación', correcta: 'd' },
  { tema: 'TEMA 20 - PROTECCIÓN DE DATOS', pregunta: '¿Qué es el Consejo Consultivo de la AEPD?', opcion_a: 'Órgano de gobierno', opcion_b: 'Órgano sancionador', opcion_c: 'Órgano judicial', opcion_d: 'Órgano asesor no vinculante', correcta: 'd' },
  { tema: 'TEMA 20 - PROTECCIÓN DE DATOS', pregunta: '¿Cada cuánto se reúne el Consejo Consultivo?', opcion_a: 'Una vez al mes', opcion_b: 'Una vez al año', opcion_c: 'Una vez al trimestre', opcion_d: 'Una vez al semestre', correcta: 'd' },
  { tema: 'TEMA 20 - PROTECCIÓN DE DATOS', pregunta: '¿Qué potestades tiene la AEPD?', opcion_a: 'Solo información', opcion_b: 'Solo asesoría', opcion_c: 'Solo formación', opcion_d: 'Investigación, inspección y sanción', correcta: 'd' },
  { tema: 'TEMA 20 - PROTECCIÓN DE DATOS', pregunta: '¿Qué condición tienen los inspectores de la AEPD?', opcion_a: 'Funcionarios ordinarios', opcion_b: 'Personal laboral', opcion_c: 'Personal eventual', opcion_d: 'Agentes de la autoridad', correcta: 'd' },
  { tema: 'TEMA 20 - PROTECCIÓN DE DATOS', pregunta: '¿Están obligados a colaborar con la AEPD?', opcion_a: 'No, es voluntario', opcion_b: 'Solo las empresas', opcion_c: 'Solo las Administraciones', opcion_d: 'Sí, Administraciones y particulares', correcta: 'd' },
  { tema: 'TEMA 20 - PROTECCIÓN DE DATOS', pregunta: '¿Qué son los planes de auditoría?', opcion_a: 'Sanciones', opcion_b: 'Inspecciones', opcion_c: 'Recursos', opcion_d: 'Auditorías preventivas de sectores concretos', correcta: 'd' },
  { tema: 'TEMA 20 - PROTECCIÓN DE DATOS', pregunta: '¿Son vinculantes las directrices de auditoría?', opcion_a: 'No, son recomendaciones', opcion_b: 'Solo si lo pide el interesado', opcion_c: 'Solo para empresas', opcion_d: 'Sí, para el sector o responsable al que se refiera', correcta: 'd' },
  { tema: 'TEMA 20 - PROTECCIÓN DE DATOS', pregunta: '¿Qué datos puede recabar la AEPD de operadoras?', opcion_a: 'Contenido de comunicaciones', opcion_b: 'Solo facturas', opcion_c: 'Ningún dato', opcion_d: 'Datos de identificación del abonado y IP', correcta: 'd' },
  { tema: 'TEMA 20 - PROTECCIÓN DE DATOS', pregunta: '¿Necesita autorización judicial para datos de tráfico?', opcion_a: 'No, nunca', opcion_b: 'Solo para empresas', opcion_c: 'Solo para particulares', opcion_d: 'Sí, en la mayoría de supuestos', correcta: 'd' },
  { tema: 'TEMA 20 - PROTECCIÓN DE DATOS', pregunta: '¿Puede acceder la AEPD a domicilio protegido?', opcion_a: 'Sí, siempre', opcion_b: 'No, nunca', opcion_c: 'Solo con orden del Ministro', opcion_d: 'Solo con consentimiento o autorización judicial', correcta: 'd' },
  { tema: 'TEMA 20 - PROTECCIÓN DE DATOS', pregunta: '¿Dónde se publican resoluciones de la AEPD?', opcion_a: 'No se publican', opcion_b: 'Solo en prensa', opcion_c: 'Solo en intranet', opcion_d: 'En su sede electrónica y BOE según corresponda', correcta: 'd' },
  { tema: 'TEMA 20 - PROTECCIÓN DE DATOS', pregunta: '¿Contra resoluciones de AEPD cabe recurso?', opcion_a: 'No, son firmes', opcion_b: 'Recurso de alzada', opcion_c: 'Recurso de reposición', opcion_d: 'Contencioso-administrativo ante Audiencia Nacional', correcta: 'd' },
  { tema: 'TEMA 20 - PROTECCIÓN DE DATOS', pregunta: '¿Qué es el Comité Europeo de Protección de Datos?', opcion_a: 'Un tribunal', opcion_b: 'Una agencia', opcion_c: 'Un ministerio', opcion_d: 'Órgano europeo donde AEPD representa a España', correcta: 'd' },
  { tema: 'TEMA 20 - PROTECCIÓN DE DATOS', pregunta: '¿Puede la AEPD cooperar internacionalmente?', opcion_a: 'No, solo en España', opcion_b: 'Solo en la UE', opcion_c: 'Solo con países hispanos', opcion_d: 'Sí, con autoridades de otros Estados', correcta: 'd' },
  { tema: 'TEMA 20 - PROTECCIÓN DE DATOS', pregunta: '¿Qué derechos digitales garantiza la LOPDGDD?', opcion_a: 'Solo derecho al olvido', opcion_b: 'Solo derecho de acceso', opcion_c: 'Solo derecho de rectificación', opcion_d: 'Derechos en internet, redes sociales, entorno laboral y educativo', correcta: 'd' },
  { tema: 'TEMA 20 - PROTECCIÓN DE DATOS', pregunta: '¿Deroga la LOPDGDD la LOPD de 1999?', opcion_a: 'No, la complementa', opcion_b: 'Solo parcialmente', opcion_c: 'La mantiene vigente', opcion_d: 'Sí, la deroga completamente', correcta: 'd' },
  { tema: 'TEMA 20 - PROTECCIÓN DE DATOS', pregunta: '¿Qué tratamiento excluye la LOPDGDD?', opcion_a: 'Ninguno', opcion_b: 'Solo tratamientos automatizados', opcion_c: 'Solo tratamientos en papel', opcion_d: 'Materias clasificadas y seguridad nacional', correcta: 'd' }
];

const stmt = db.prepare("INSERT INTO preguntas (tema, pregunta, opcion_a, opcion_b, opcion_c, opcion_d, correcta) VALUES (?, ?, ?, ?, ?, ?, ?)");
const insertMany = db.transaction((qs) => {
  for (const q of qs) {
    stmt.run(q.tema, q.pregunta, q.opcion_a, q.opcion_b, q.opcion_c, q.opcion_d, q.correcta);
  }
});
insertMany(questions);
console.log('Seeded TEMA 20 questions');
